name: OpsDev-CI
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  explore-github-actions:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        ref: main



